spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://olysystem.iptime.org:23306/sp_blog?serviceTimeZone=UTC&CharacterEncoding=UTF-8
    username: user_sw
    password: Sw123!@# 
    mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 8080